name: Keep Alive Ping

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server 1
        run: |
          curl -s https://tamdtnek13102005-ssh.hf.space/?folder=/workspace
          echo "✅ Pinged Server 1 at $(date)"

      - name: Ping Server 2
        run: |
          curl -s https://tamdtnek13102005-hadoop.hf.space/?folder=/workspace
          echo "✅ Pinged Server 2 at $(date)"
      - name: Ping Server 1
        run: |
          curl -s https://tamdtnek13102005-hadoopgk.hf.space/?folder=/workspace
          echo "✅ Pinged Server 3 at $(date)"
